# Generated by Django 3.1.4 on 2020-12-15 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('period', models.IntegerField()),
                ('reason', models.TextField()),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
