# Generated by Django 3.1.4 on 2020-12-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20201216_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
