# Generated by Django 3.1.4 on 2020-12-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_monthes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
