# Generated by Django 3.1.4 on 2020-12-16 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20201216_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='loan.loan'),
        ),
    ]
