# Generated by Django 3.1.4 on 2020-12-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20201216_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
