# Generated by Django 3.1.4 on 2020-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20201216_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
    ]
