# Generated by Django 3.1.4 on 2020-12-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_auto_20201216_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='paid_monthes',
            new_name='rest_paymrnts',
        ),
    ]
