# Generated by Django 3.1.4 on 2020-12-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_auto_20201216_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='loan.loan'),
        ),
    ]
